//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loupedeck.TwitchPlugin.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Loupedeck.TwitchPlugin.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Day.
        /// </summary>
        internal static string _1_Day {
            get {
                return ResourceManager.GetString("1 Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Hour.
        /// </summary>
        internal static string _1_Hour {
            get {
                return ResourceManager.GetString("1 Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Month.
        /// </summary>
        internal static string _1_Month {
            get {
                return ResourceManager.GetString("1 Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Sec.
        /// </summary>
        internal static string _1_Sec {
            get {
                return ResourceManager.GetString("1 Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Week.
        /// </summary>
        internal static string _1_Week {
            get {
                return ResourceManager.GetString("1 Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 Minutes.
        /// </summary>
        internal static string _10_Minutes {
            get {
                return ResourceManager.GetString("10 Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 Sec.
        /// </summary>
        internal static string _10_Sec {
            get {
                return ResourceManager.GetString("10 Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120 Sec.
        /// </summary>
        internal static string _120_Sec {
            get {
                return ResourceManager.GetString("120 Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 Sec.
        /// </summary>
        internal static string _15_Sec {
            get {
                return ResourceManager.GetString("15 Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150 Sec.
        /// </summary>
        internal static string _150_Sec {
            get {
                return ResourceManager.GetString("150 Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180 Sec.
        /// </summary>
        internal static string _180_Sec {
            get {
                return ResourceManager.GetString("180 Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Months.
        /// </summary>
        internal static string _3_Months {
            get {
                return ResourceManager.GetString("3 Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Sec.
        /// </summary>
        internal static string _3_Sec {
            get {
                return ResourceManager.GetString("3 Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 Minutes.
        /// </summary>
        internal static string _30_Minutes {
            get {
                return ResourceManager.GetString("30 Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 Sec.
        /// </summary>
        internal static string _30_Sec {
            get {
                return ResourceManager.GetString("30 Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Sec.
        /// </summary>
        internal static string _5_Sec {
            get {
                return ResourceManager.GetString("5 Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 Sec.
        /// </summary>
        internal static string _60_Sec {
            get {
                return ResourceManager.GetString("60 Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90 Sec.
        /// </summary>
        internal static string _90_Sec {
            get {
                return ResourceManager.GetString("90 Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban.
        /// </summary>
        internal static string Ban {
            get {
                return ResourceManager.GetString("Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followers-Only.
        /// </summary>
        internal static string Followers_Only {
            get {
                return ResourceManager.GetString("Followers-Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lift Ban/Timeout.
        /// </summary>
        internal static string Lift_Ban_Timeout {
            get {
                return ResourceManager.GetString("Lift Ban/Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Commercial.
        /// </summary>
        internal static string Run_Commercial {
            get {
                return ResourceManager.GetString("Run Commercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow Mode.
        /// </summary>
        internal static string Slow_Mode {
            get {
                return ResourceManager.GetString("Slow Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
    }
}
